AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for Bank App

Resources:
  DynamoDB:
    Type: AWS::Serverless::Application
    Properties:
      Location: cloudformation/dynamodb.yaml
  Functions:
    Type: AWS::Serverless::Application
    Properties:
      Location: cloudformation/functions.yaml
      Parameters:
        TransactionsTableArn: !GetAtt DynamoDB.Outputs.TransactionsTableArn
        TransactionsTableStreamArn: !GetAtt DynamoDB.Outputs.TransactionsTableStreamArn
        AccountsTableArn: !GetAtt DynamoDB.Outputs.AccountsTableArn
        UsersTableArn: !GetAtt DynamoDB.Outputs.UsersTableArn
  Policies:
    Type: AWS::Serverless::Application
    Properties:
      Location: cloudformation/policies.yaml
      Parameters:
        ExecuteTransactionStfArn: !GetAtt Functions.Outputs.ExecuteTransactionStfArn
        ExecutePaymentFunctionArn: !GetAtt Functions.Outputs.ExecutePaymentFunctionArn
        RequestPaymentFunctionArn: !GetAtt Functions.Outputs.RequestPaymentFunctionArn
        ExecutePaymentLambdaRole: !GetAtt Functions.Outputs.ExecutePaymentLambdaRole
        RequestPaymentLambdaRole: !GetAtt Functions.Outputs.RequestPaymentLambdaRole
        AddCreditsLambdaRole: !GetAtt Functions.Outputs.AddCreditsLambdaRole
        CreateUserLambdaRole: !GetAtt Functions.Outputs.CreateUserLambdaRole
        ExecuteTransactionStfRole: !GetAtt Functions.Outputs.ExecuteTransactionStfRole
        BankApiRole: !GetAtt Functions.Outputs.BankApiRole
        TransactionsTableArn: !GetAtt DynamoDB.Outputs.TransactionsTableArn
        TransactionsTableStreamArn: !GetAtt DynamoDB.Outputs.TransactionsTableStreamArn
        AccountsTableArn: !GetAtt DynamoDB.Outputs.AccountsTableArn
        UsersTableArn: !GetAtt DynamoDB.Outputs.UsersTableArn